services:
  frontend:
    build:
      context: ./Frontend-React
      dockerfile: Dockerfile.dev
    container_name: frontend_app
    volumes:
      - ./Frontend-React:/app
      - /app/node_modules
    ports:
      - ${FRONTEND_PORT}:5173
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
    networks:
      - full-network

  backend:
    build:
      context: ./Backend-Express
      dockerfile: Dockerfile.dev
    container_name: backend_app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - "./Backend-Express:/app"
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=mysql://${MYSQL_ROOT_HOST}:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}

    depends_on:
      - mysql
      - redis
    networks:
      - full-network
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate dev &&
             npm run dev"

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - full-network
  
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "3310:${REDIS_PORT}"
    networks:
      - full-network

  caddy:
    image: abiosoft/caddy
    container_name: caddy
    ports:
      - '80:80'
    volumes:
      - './Caddyfile:/etc/Caddyfile'
      - './src:/srv'

networks:
  full-network: {}

volumes:
  mysql_data: {}
